site_name: SSE Documentation Example
site_url: https://cheriimoya.github.io/sse-mkdocs-exercise/
site_author: cheriimoya
repo_url: https://github.com/cheriimoya/sse-mkdocs-exercise

theme:
    name: readthedocs
    locale: en

nav:
  - Home: index.md
  - User Guide:
    - Installation: compilation-and-installation.md
    - Getting Started: how-to.md
